### Word Embedding Techniques using Embedding Layer in Keras

In [2]:
### Libraries USed Tensorflow> 2.0  and keras

In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[2177, 5072, 3640, 6310], [2177, 5072, 3640, 3369], [2177, 8580, 3640, 7972], [5557, 7285, 8737, 222, 2136], [5557, 7285, 8737, 222, 7125], [5757, 2177, 8474, 3640, 9259], [7094, 9992, 8640, 222]]


### Word Embedding Represntation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2177 5072 3640 6310]
 [   0    0    0    0 2177 5072 3640 3369]
 [   0    0    0    0 2177 8580 3640 7972]
 [   0    0    0 5557 7285 8737  222 2136]
 [   0    0    0 5557 7285 8737  222 7125]
 [   0    0    0 5757 2177 8474 3640 9259]
 [   0    0    0    0 7094 9992 8640  222]]


In [13]:
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

D:\apps\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step
[[[-0.04218044  0.00923026 -0.02368474  0.02719257 -0.04168089
    0.04614021 -0.01588637 -0.03530545  0.03394827 -0.04714603]
  [-0.04218044  0.00923026 -0.02368474  0.02719257 -0.04168089
    0.04614021 -0.01588637 -0.03530545  0.03394827 -0.04714603]
  [-0.04218044  0.00923026 -0.02368474  0.02719257 -0.04168089
    0.04614021 -0.01588637 -0.03530545  0.03394827 -0.04714603]
  [-0.04218044  0.00923026 -0.02368474  0.02719257 -0.04168089
    0.04614021 -0.01588637 -0.03530545  0.03394827 -0.04714603]
  [ 0.00755589  0.02021546  0.01927222  0.04904026 -0.02142239
   -0.00368448  0.00239952  0.01964456 -0.00802426  0.0286756 ]
  [ 0.00184376  0.03906449 -0.00369138  0.03856843 -0.04656864
   -0.0094502   0.02243713  0.0307082  -0.02860232  0.03104991]
  [ 0.04149124  0.04292735  0.01290913  0.01391998  0.01746095
    0.01343468  0.0264861   0.03953746 -0.0105201  -0.04093502]
  [-0.04471472 -0.04177543  0.00954487  0.04640507  0.02894243
   -0.004

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 2177, 5072, 3640, 6310])

In [18]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[-0.04218044  0.00923026 -0.02368474  0.02719257 -0.04168089  0.04614021
  -0.01588637 -0.03530545  0.03394827 -0.04714603]
 [-0.04218044  0.00923026 -0.02368474  0.02719257 -0.04168089  0.04614021
  -0.01588637 -0.03530545  0.03394827 -0.04714603]
 [-0.04218044  0.00923026 -0.02368474  0.02719257 -0.04168089  0.04614021
  -0.01588637 -0.03530545  0.03394827 -0.04714603]
 [-0.04218044  0.00923026 -0.02368474  0.02719257 -0.04168089  0.04614021
  -0.01588637 -0.03530545  0.03394827 -0.04714603]
 [ 0.00755589  0.02021546  0.01927222  0.04904026 -0.02142239 -0.00368448
   0.00239952  0.01964456 -0.00802426  0.0286756 ]
 [ 0.00184376  0.03906449 -0.00369138  0.03856843 -0.04656864 -0.0094502
   0.02243713  0.0307082  -0.02860232  0.03104991]
 [ 0.04149124  0.04292735  0.01290913  0.01391998  0.01746095  0.01343468
   0.0264861   0.03953746 -0.0105201  -0.04093502]
 [-0.04471472 -0.04177543  0.00954487  0.04640507  0.02894243 -0.00453829
   0.02891687 